import typing
import pathlib

type _IO = str | pathlib.Path | typing.BinaryIO

class Vocabulary:
    @staticmethod
    def read_from(src: _IO) -> 'Vocabulary': ...
    def write_to(self, dst: _IO): ...
    @property
    def k(self) -> int: ...
    @property
    def desc_name(self) -> str: ...
    def __len__(self) -> int: ...
    def clear(self): ...

class VocabularyCreatorParams:
    k: int
    L: int | None
    max_iters: int
    nthreads: int
    verbose: bool
    def __init__(self, k: int = ..., L: int | None = None, max_iters: int = ..., nthreads: int = ..., verbose: bool = ...): ...

class VocabularyCreator:
    def __init__(self, params: VocabularyCreatorParams): ...
    def create(self, *args): ...

class FBOW:
    ...
class FBOW2:
    ...