import typing
import pathlib
import numpy as np
from collections.abc import Sequence
from enum import Enum, auto

type _IO = str | pathlib.Path | typing.BinaryIO

type _FeatureU8[F: int] = np.ndarray[tuple[int, F], np.dtype[np.uint8]]
type _FeatureF32[F: int] = np.ndarray[tuple[int, F], np.dtype[np.uint8]]

class Scoring(Enum):
	L1 = auto()
	L2 = auto()
	ChiSquare = auto()
	KL = auto()
	Bhattacharyya = auto()
	DotProduct = auto()

class FBOW:
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...
	def keys(self, sorted: bool = False) -> list[int]: ...
	def __getitem__(self, key: int) -> float | None: ...
	def score(self, other: 'FBOW', metric: Scoring = Scoring.L2) -> float: ...
	def norm(self) -> float: ...
	def normalize(self) -> 'FBOW': ...

class FBOW2:
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...
	def keys(self, sorted: bool = False) -> list[int]: ...
	def __getitem__(self, key: int) -> list[int] | None: ...


class Vocabulary[T: np.uint8 | np.float32]:
	@staticmethod
	def from_bytes(src: bytes) -> 'Vocabulary':
		"Deserialize vocabulary from bytes"
		...
	@staticmethod
	def read_from(src: _IO) -> 'Vocabulary':
		"Read vocabulary from file"
		...
	def write_to(self, dst: _IO):
		"Write vocabulary to file"
		...
	def to_bytes(self) -> bytes:
		"Serialize vocabulary to bytes"
		...
	
	@property
	def k(self) -> int: ...
	@property
	def num_features(self) -> int: ...
	@property
	def desc_name(self) -> str: ...
	def print_tree(self): ...
	def transform(self, features: np.ndarray, max_depth: int | None = None) -> tuple[FBOW, FBOW2]: ...
	def __len__(self) -> int: ...

class VocabularyCreatorParams:
	k: int
	L: int | None
	max_iters: int
	nthreads: int
	verbose: bool
	def __init__(self, k: int = ..., L: int | None = None, max_iters: int = ..., nthreads: int = ..., verbose: bool = ...): ...

class VocabularyCreator:
	def __init__(self, params: VocabularyCreatorParams): ...
	def create[F: int](self, features: _FeatureU8[F] | _FeatureF32[F] | Sequence[_FeatureU8[F]] | Sequence[_FeatureF32[F]], desc_name: str) -> Vocabulary: ...