import typing
import pathlib
import numpy as np
from collections.abc import Sequence, Iterator
from enum import Enum, auto

type _IO = str | pathlib.Path | typing.BinaryIO

type _FeatureU8[F: int] = np.ndarray[tuple[int, F], np.dtype[np.uint8]]
type _FeatureF32[F: int] = np.ndarray[tuple[int, F], np.dtype[np.uint8]]

class LNorm(Enum):
	L1 = auto()
	"L1 norm (manhattan distance)"
	L2 = auto()
	"L2 norm (euclidean distance)"

class Scoring(Enum):
	L1 = auto()
	L2 = auto()
	ChiSquare = auto()
	KL = auto()
	Bhattacharyya = auto()
	DotProduct = auto()

class _PyDictView:
	def __bool__(self) -> bool: ...
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...

class _BowKeys(_PyDictView):
	def __iter__(self) -> Iterator[int]: ...
	def to_list(self, sorted: bool = False) -> list[int]: ...
	def to_numpy(self, sorted: bool = False) -> np.ndarray[tuple[int], np.dtype[np.uint32]]: ...

class _BowValues(_PyDictView):
	def __iter__(self) -> Iterator[float]: ...
	def to_list(self, sorted: bool = False) -> list[int]: ...
	def to_numpy(self, sorted: bool = False) -> np.ndarray[tuple[int], np.dtype[np.uint32]]: ...

class _BowItems(_PyDictView):
	def __iter__(self) -> Iterator[tuple[int, float]]: ...
	def to_list(self, sorted: bool = False) -> list[int]: ...
	def to_numpy(self, sorted: bool = False) -> np.ndarray[tuple[int], np.dtype[np.uint32]]: ...

class Bow:
	"Bag of words"
	def __bool__(self) -> bool: ...
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...
	def __hash__(self) -> int: ...
	def __contains__(self, key: int) -> bool: ...

	def keys(self) -> _BowKeys: ...
	def values(self) -> _BowValues: ...
	def items(self) -> _BowItems: ...

	def get[T](self, key: int, default: T) -> float | T: ...
	def __getitem__(self, key: int) -> float: ...

	def score(self, other: 'Bow', metric: Scoring = Scoring.L2) -> float:
		"Compute the score between this and some other bag of words"
		...
	def norm(self, norm: LNorm = LNorm.L2) -> float:
		"Compute the Ln norm of all the scores"
		...
	def normalize(self, norm: LNorm = LNorm.L2) -> 'Bow':
		"Normalize such that `fbow.normalize().norm() == 1.0`"
		...
	def to_dict(self) -> dict[int, float]:
		"Convert to native Python dict"
		...

class _FeaturesKeys(_PyDictView):
	def __iter__(self) -> Iterator[int]: ...
	def to_list(self, sorted: bool = False) -> list[int]: ...
	def to_numpy(self, sorted: bool = False) -> np.ndarray[tuple[int], np.dtype[np.uint32]]: ...

class _FeaturesValues(_PyDictView):
	def __iter__(self) -> Iterator[list[int]]: ...
	def to_list(self, sorted: bool = False) -> list[list[int]]: ...
	def to_numpy(self, sorted: bool = False) -> np.ndarray[tuple[int], np.dtype[np.uint32]]: ...

class _FeaturesItems(_PyDictView):
	def __iter__(self) -> Iterator[tuple[int, list[int]]]: ...
	def to_list(self, sorted: bool = False) -> list[int]: ...
	def to_numpy(self, sorted: bool = False) -> np.ndarray[tuple[int], np.dtype[np.uint32]]: ...

class _IntersectFeatures:
	"Intersection of features"
	def __bool__(self) -> int: ...
	def __len__(self) -> int: ...
	def keys(self) -> list[int]: ...
	def values(self) -> list[tuple[list[int], ...]]: ...
	def __iter__(self) -> Iterator[tuple[int, tuple[list[int], ...]]]: ...
	def __and__(self, other: 'Features | _IntersectFeatures') -> _IntersectFeatures: ...

class Features:
	"""
	Bag of words with augmented information.

	For each word, keeps information about the indices of the elements that have been classified into the word.
	It is computed at the desired level
	"""
	def __bool__(self) -> bool: ...
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...
	def __hash__(self) -> int: ...

	def __getitem__(self, key: int) -> list[int]: ...
	def __contains__(self, key: int) -> bool: ...
	def get[T](self, key: int, default: T) -> list[int] | T: ...
	
	def keys(self) -> _FeaturesKeys: ...
	def values(self) -> _FeaturesValues: ...
	def items(self) -> _FeaturesItems: ...
	def to_dict(self) -> dict[int, list[int]]: ...

	def __and__(self, other: 'Features | _IntersectFeatures') -> _IntersectFeatures: ...

class ParseValidationMode(Enum):
	Ignore = auto()
	"Silently accept invalid data"
	Warn = auto()
	"Print a message to stdout"
	Strict = auto()
	"Return an error on invalid data"

class Vocabulary[T: np.uint8 | np.float32]:
	@staticmethod
	def from_bytes(src: bytes, level: ParseValidationMode | None = None) -> 'Vocabulary':
		"Deserialize vocabulary from bytes"
		...
	@staticmethod
	def read_from(src: _IO, level: ParseValidationMode | None = None) -> 'Vocabulary':
		"Read vocabulary from file"
		...
	def write_to(self, dst: _IO):
		"Write vocabulary to file"
		...
	def to_bytes(self) -> bytes:
		"Serialize vocabulary to bytes"
		...
	
	def print_tree(self):
		"Print tree to stdout"
		...
	@property
	def k(self) -> int:
		"Branching factor 'k'"
		...
	@property
	def num_features(self) -> int: ...
	@property
	def desc_name(self) -> str: ...
	def __len__(self) -> int:
		"Get total nuber of blocks"
		...
	def __str__(self) -> str: ...
	def __repr__(self) -> str: ...
	def features(self) -> np.ndarray[tuple[int, int], T]:
		"Copy features to numpy array"
		...
	
	def transform(self, features: np.ndarray[tuple[int, int], T], max_depth: int | None = None) -> tuple[Bow, Features]: ...

class VocabularyCreatorParams:
	"Parameters for [VocabularyCreator]"
	k: int
	"Branching factor"
	L: int | None
	"Maximum tree depth"
	max_iters: int
	"Number of k-means iterations"
	nthreads: int
	"Number of threads to use while computing"
	verbose: bool
	def __init__(self, k: int = 32, L: int | None = None, max_iters: int = 11, nthreads: int = 1, verbose: bool = False): ...
	def effective_threads(self) -> int: ...
	def __str__(self) -> str: ...
	def __repr__(self) -> str: ...
	def __eq__(self, value, /) -> bool: ...
	def __ne__(self, value, /) -> bool: ...
	def __hash__(self) -> int: ...

class VocabularyCreator:
	"Helper to create a [Vocabulary]"
	def __init__(self, params: VocabularyCreatorParams = ...): ...
	@property
	def params(self) -> VocabularyCreatorParams: ...
	
	def create[F: int](self, features: _FeatureU8[F] | _FeatureF32[F] | Sequence[_FeatureU8[F]] | Sequence[_FeatureF32[F]], desc_name: str) -> Vocabulary: ...


class QueryResult:
	score: float
	id: int

class QueryResults:
	def ids(self) -> list[int]:
		"Get ids"
		...
	def scores(self) -> list[float]:
		"Get scores"
		...
	def to_list(self) -> list[QueryResult]: ...
	def __bool__(self) -> bool: ...
	def __len__(self) -> int: ...
	def __getitem__(self, idx: int) -> QueryResult | None: ...

class Database:
	def __init__(self, vocabulary: Vocabulary, use_direct: bool = True, di_levels: int = 0): ...
	def __bool__(self) -> bool: ...
	def __len__(self) -> int: ...
	@property
	def vocabulary(self) -> Vocabulary: ...
	@typing.overload
	def insert_transform(self, features: _FeatureU8 | _FeatureF32) -> int: ...
	@typing.overload
	def insert_transform(self, features: Sequence[_FeatureU8] | Sequence[_FeatureF32]) -> list[int]: ...
	def insert(self, bow: Bow, features: Features) -> int: ...
	def query(self, query: Bow, scoring: Scoring, max_results: int | None = None, max_id: int | None = None) -> QueryResults: ...
	def clear(self) -> None: ...